Name:Leo Jamu
Date:1/29/2026
Program of study:Bachelor of Science in computer science
much passion for data science
 Experiment 5
Aim:To perform operation for creation of an data frame

In [1]:
import pandas as pd

In [ ]:
#creating ones one dataframe
#pd.DataFrame(): Creates a 2D table (like Excel sheet)

#First argument: List of lists = rows of data

#columns: Names for each column

df = pd.DataFrame([[10,15,20,16],[19,17,15,13],[15,19,17,14]],
                  columns=["CD","DBMS","DSS","CAO"])

In [14]:
#pd.DataFrame(): Creates a 2D table (like Excel sheet)

#First argument: List of lists = rows of data

#columns: Names for each column

df #visualization of data frame

   CD  DBMS  DSS  CAO
0  10    15   20   16
1  19    17   15   13
2  15    19   17   14

In [15]:
df.shape    # Returns (3, 4) → (rows, columns)

(3, 4)

In [16]:
df.size     # Returns 12 → total cells (3×4)

12

In [17]:
df.ndim     # Returns 2 → 2-dimensional table

2

In [18]:


# Create new DataFrame with 1 row

df2=pd.DataFrame([[5,6,7,8]],
                columns=["CD","DBMS","DSS","CAO"])

In [19]:
df2

   CD  DBMS  DSS  CAO
0   5     6    7    8

In [23]:
# Append with reset index
df3=pd.concat([df, df2], ignore_index=True)

In [24]:
df3

   CD  DBMS  DSS  CAO
0  10    15   20   16
1  19    17   15   13
2  15    19   17   14
3   5     6    7    8

In [25]:
df3["DM"] = [12,15,17,19]  # Add new column "DM" (Data Mining)

In [26]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    15   20   16  12
1  19    17   15   13  15
2  15    19   17   14  17
3   5     6    7    8  19

In [27]:
# Delete ROWS by index
df4 = df3.drop(index=[1])  # Remove row with index 1

In [28]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    15   20   16  12
2  15    19   17   14  17
3   5     6    7    8  19

In [29]:
# Delete COLUMNS by name  
df5 = df3.drop(columns=["DM"])  # Remove "DM" column

In [30]:
df5

   CD  DBMS  DSS  CAO
0  10    15   20   16
1  19    17   15   13
2  15    19   17   14
3   5     6    7    8

In [31]:
#finding mean of DSS
print("Mean of DSS:",df5["DSS"].mean())

Mean of DSS: 14.75

In [32]:
#finding median of DSS
print("Median of DSS:",df5["DSS"].median())

Median of DSS: 16.0

In [33]:
#finding mode of DSS,Most frequent: all appear once

print("Mode of DSS:",df5["DSS"].mode())

Mode of DSS: 0     7
1    15
2    17
3    20
Name: DSS, dtype: int64

In [34]:
#finding max of DSS
print("Max of DSS:",df5["DSS"].max())

Max of DSS: 20

In [35]:
#finding min of DSS
print("Min of DSS:",df5["DSS"].min())

Min of DSS: 7

In [36]:
#Series Creation (1D Data)
Name=["Shriram","Shrihari","Harshal","Kartik","Rohan"]
Name

['Shriram', 'Shrihari', 'Harshal', 'Kartik', 'Rohan']

In [37]:
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1     Shriram
2    Shrihari
3     Harshal
4      Kartik
5       Rohan
dtype: object

Conclusion:-In this experiment, we successfully learned how to create and manipulate DataFrames using the Pandas library in Python.